/**
 * The project home.
 *
 * The four primary actions are the product's front door (acceptance W02), and
 * "Make Something From an Image" is deliberately the largest, first and
 * highest-contrast thing on the page - the lesson from every
 * image-in/playable-out tool is that the entry point should not be behind
 * engine setup (section 18).
 */

import { button, el, maturityBadgeClass, replace, toast } from '../dom.ts';
import { getState, subscribe, type AppState } from '../state.ts';
import { goPresets, openProject, refreshProjects } from '../actions.ts';
import { openCreateDialog } from './createDialog.ts';
import { openImportFirstFlow } from './importFirstFlow.ts';
import * as api from '../api.ts';

function actionCard(
  icon: string,
  title: string,
  description: string,
  onClick: () => void,
  hero = false,
): HTMLElement {
  return el(
    'button',
    { class: `action${hero ? ' action--hero' : ''}`, attrs: { type: 'button' }, on: { click: onClick } },
    el('div', { class: 'action__icon', text: icon }),
    el('div', { class: 'action__title', text: title }),
    el('div', { class: 'action__desc', text: description }),
  );
}

function projectCard(summary: AppState['projects'][number]): HTMLElement {
  const thumb = el('div', { class: 'card__thumb' }, el('span', { class: 'faint', text: 'no art yet' }));
  if (summary.thumbnailAssetId) {
    const image = el('img', { attrs: { alt: '', loading: 'lazy' } });
    // The asset endpoint is same-origin and hash-versioned; a broken one falls
    // back to the placeholder rather than a broken-image icon.
    image.src = api.assetUrl(summary.gameId, summary.thumbnailAssetId, summary.gameId);
    image.onerror = () => replace(thumb, el('span', { class: 'faint', text: 'no art yet' }));
    replace(thumb, image);
  }

  return el(
    'button',
    { class: 'card', attrs: { type: 'button' }, on: { click: () => void openProject(summary.gameId) } },
    thumb,
    el(
      'div',
      { class: 'card__head' },
      el('span', { class: 'card__name truncate', text: summary.displayName }),
      el('span', { class: maturityBadgeClass(summary.maturity), text: summary.maturity }),
    ),
    el(
      'div',
      { class: 'card__meta' },
      el('span', { class: 'mono', text: summary.presetId }),
      el('span', { text: `${summary.assetCount} asset${summary.assetCount === 1 ? '' : 's'}` }),
      el('span', { text: summary.lastBuildState === 'packed' ? 'packed' : summary.lastBuildState === 'built' ? 'built' : 'not built' }),
      !summary.hasWorkbenchMetadata ? el('span', { class: 'badge', text: 'adopt on open' }) : null,
      summary.provenanceBlocked ? el('span', { class: 'badge badge--danger', text: 'provenance blocks release' }) : null,
    ),
  );
}

export function renderHome(host: HTMLElement): () => void {
  const projectsHost = el('div');

  function paint(state: AppState): void {
    replace(
      projectsHost,
      state.projects.length === 0
        ? el(
            'div',
            { class: 'empty' },
            el('strong', { text: 'No games here yet' }),
            el('div', { text: 'Start with an image you already have, or pick a preset and build up from there.' }),
          )
        : el('div', { class: 'cards' }, ...state.projects.map(projectCard)),
    );
  }

  replace(
    host,
    el(
      'div',
      { class: 'home' },
      el(
        'div',
        { class: 'home__inner' },
        el('h1', { class: 'home__title', text: 'Stinky Weasel Game Factory' }),
        el('p', {
          class: 'home__sub',
          text: 'Give it something you already have - one image, a folder of art, a sprite sheet - and it turns that into a real, playable SW2D game you can refine, preview and package here. Everything runs on this machine: no account, no API key, no upload.',
        }),
        el(
          'div',
          { class: 'actions' },
          actionCard(
            '🖼️',
            'Make Something From an Image',
            'Import one image, see candidate playable directions built from it, and pick one. You get a real game, not a mockup.',
            () => void openImportFirstFlow(),
            true,
          ),
          actionCard('🗂️', 'Create From Assets', 'Start a project, then bring in a folder, a sprite sheet or a ZIP of art and map it onto game roles.', () =>
            openCreateDialog({ mode: 'assets' }),
          ),
          actionCard('📂', 'Open Existing Project', 'Reopen a game you made here, or adopt one generated by the CLI - your assets, roles and layout come back.', () => {
            const { projects } = getState();
            if (projects.length === 0) {
              toast('No projects under games/ yet. Make one first.', 'warn');
              return;
            }
            document.getElementById('recent-projects')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
          }),
          actionCard('🎛️', 'Browse Presets', 'All 74 genre recipes, with honest maturity, required packs and known limitations.', () => goPresets()),
        ),
        el('div', { attrs: { id: 'recent-projects' } }, el('h2', { class: 'section-title', text: 'Your games' }), projectsHost),
        el(
          'div',
          { style: { 'margin-top': '30px' } },
          el('h2', { class: 'section-title', text: 'What this is running on' }),
          el(
            'div',
            { class: 'infobox' },
            el('div', { text: 'This workbench drives the SW2D factory directly: the same generator, schemas, content pipeline and release packer the command line uses. Games it makes are ordinary SW2D projects - editable outside the workbench, and buildable without it.' }),
          ),
        ),
      ),
    ),
  );

  paint(getState());
  void refreshProjects();
  return subscribe(paint);
}

/** Kept for the preset browser's "create from this preset" path. */
export { openCreateDialog };
export { button };
