import type { ConstructionDocument, ConstructionResult, ConstructionService, ConstructionSite, GameContext, InstalledSystemPack, Point, SystemPackDefinition } from '@sw2d/contracts';
import { placementReason, validateConstructionDocument } from '@sw2d/contracts';
import { CAPABILITY_IDS, PACK_IDS } from '../ids.ts';
import type { NavService } from '@sw2d/contracts';
class ConstructionServiceImpl implements ConstructionService {
  readonly #doc: ConstructionDocument; readonly #sites = new Map<string, ConstructionSite>(); #resources: number; #next = 1;
  readonly #routeIntact: (rect: { readonly x: number; readonly y: number; readonly width: number; readonly height: number }) => boolean;
  constructor(doc: ConstructionDocument, navigation?: NavService) { validateConstructionDocument(doc); this.#doc = doc; this.#resources = doc.startingResources; this.#routeIntact = (rect) => { const nav = doc.navigation; const grid = nav ? navigation?.grid(nav.gridId) : undefined; if (!nav || !grid) return false; const from = grid.worldToCell(rect.x, rect.y); const to = grid.worldToCell(rect.x + rect.width, rect.y + rect.height); const changed: { col: number; row: number; walkable: boolean }[] = []; for (let row = Math.min(from.row, to.row); row <= Math.max(from.row, to.row); row++) for (let col = Math.min(from.col, to.col); col <= Math.max(from.col, to.col); col++) { const walkable = grid.isWalkable(col, row); changed.push({ col, row, walkable }); grid.setWalkable(col, row, false); } try { return nav.requiredRoutes.every((route) => grid.findPath(route.from, route.to) !== null); } finally { for (const cell of changed) grid.setWalkable(cell.col, cell.row, cell.walkable); } }; }
  resources() { return this.#resources; } sites() { return [...this.#sites.values()].sort((a, b) => a.id.localeCompare(b.id)); }
  preview(id: string, position: Point): ConstructionResult { const b = this.#doc.buildables.find((x) => x.id === id); if (!b) return fail('unknown-buildable'); const reason = placementReason(this.#doc, this.sites(), b, position, this.#routeIntact); return reason ? fail(reason) : this.#resources < b.cost ? fail('insufficient-resources') : ok(); }
  place(id: string, position: Point): ConstructionResult { const result = this.preview(id, position); if (!result.ok) return result; const b = this.#doc.buildables.find((x) => x.id === id)!; this.#resources -= b.cost; const siteId = `site-${this.#next++}`; this.#sites.set(siteId, { id: siteId, buildableId: id, position, phase: 'blueprint', progressMs: 0, workerId: null, paidCost: b.cost }); return { ok: true, siteId }; }
  assign(id: string, workerId: string): ConstructionResult { const site = this.#sites.get(id); if (!site) return fail('unknown-site'); if (site.phase !== 'blueprint' && site.phase !== 'building') return fail('wrong-phase'); this.#sites.set(id, { ...site, phase: 'building', workerId }); return ok(); }
  advance(deltaMs: number) { for (const site of this.sites()) { if (site.phase !== 'building') continue; const b = this.#doc.buildables.find((x) => x.id === site.buildableId)!; const progressMs = Math.min(b.durationMs, site.progressMs + Math.max(0, deltaMs)); this.#sites.set(site.id, { ...site, progressMs, phase: progressMs >= b.durationMs ? 'complete' : 'building' }); } }
  cancel(id: string): ConstructionResult { const site = this.#sites.get(id); if (!site) return fail('unknown-site'); if (site.phase === 'complete' || site.phase === 'cancelled') return fail('wrong-phase'); const b = this.#doc.buildables.find((x) => x.id === site.buildableId)!; this.#resources += Math.floor(site.paidCost * (b.refundRatio ?? 0)); this.#sites.set(id, { ...site, phase: 'cancelled', workerId: null }); return ok(); }
  deconstruct(id: string): ConstructionResult { const site = this.#sites.get(id); if (!site) return fail('unknown-site'); if (site.phase !== 'complete') return fail('wrong-phase'); const b = this.#doc.buildables.find((x) => x.id === site.buildableId)!; this.#resources += Math.floor(site.paidCost * (b.refundRatio ?? 0)); this.#sites.set(id, { ...site, phase: 'cancelled', workerId: null }); return ok(); }
}
const ok = (): { readonly ok: true } => ({ ok: true }); const fail = (reason: Exclude<ConstructionResult, { ok: true }>['reason']): ConstructionResult => ({ ok: false, reason });
export const constructionPack: SystemPackDefinition<undefined, GameContext> = { id: PACK_IDS.construction, version: '0.1.0', provides: [CAPABILITY_IDS.construction], dependencies: [], install(context): InstalledSystemPack { const doc = context.content.data.construction?.value as ConstructionDocument | undefined; if (!doc) throw new Error('sw2d.construction requires content/construction.json.'); const service = new ConstructionServiceImpl(doc, context.capabilities.has(CAPABILITY_IDS.navigation) ? context.capabilities.require<NavService>(CAPABILITY_IDS.navigation) : undefined); const handle = context.capabilities.provide(CAPABILITY_IDS.construction, service); return { id: PACK_IDS.construction, update: (ms) => service.advance(ms), dispose: () => handle.dispose() }; } };
export { ConstructionServiceImpl }; export type { ConstructionService } from '@sw2d/contracts';
