import { spawnSync } from 'node:child_process';
import { existsSync, rmSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PRESETS } from '@sw2d/presets';
import { findSystemChrome, runSmoke } from '@sw2d/qa';
import { buildGameFiles, writeGameFiles } from '../../packages/cli/src/generator/generate.ts';
import { ensureWorkspaceInstalled } from '../../packages/cli/src/workspace.ts';

/**
 * `npm run qa:completion` - the Final Product Completion program's
 * generated-game journeys (docs/architecture/FINAL_PRODUCT_COMPLETION_MATRIX.md).
 *
 * The rule the program is held to: a limitation is closed only when a game
 * freshly generated by the canonical factory - not a frozen proof fixture,
 * not an overlay kit - visibly provides the genre behaviour. So for every
 * preset listed here this runner (1) generates `games/final-<id>` through
 * the same `buildGameFiles` path `sw2d new` and the Workbench use, (2) runs a
 * real `vite build`, (3) plays the preset's completion journey in system
 * Chrome through the shared `runSmoke()` oracle (zero console errors, zero
 * external requests, plus the spec's own assertions), then (4) removes the
 * generated game. Optional positional filters narrow the run.
 *
 * Specs live in `packages/qa/completion-specs/`. Where a preset's committed
 * proof is itself unmodified canonical output, the completion spec re-exports
 * the proof spec - one journey, two entry points (frozen proof and fresh
 * generation), no drift.
 */

const REPO_ROOT = path.resolve(fileURLToPath(new URL('.', import.meta.url)), '../..');
const GAMES_ROOT = path.join(REPO_ROOT, 'games');

export const COMPLETION_SPEC_MODULES: Readonly<Record<string, string>> = {
  // Wave 1 - platforming movement (L01 pursuit wall, L02 runner chaser, L03 ledge grammar)
  'chase-platformer': 'chasePlatformer',
  'endless-runner': 'endlessRunner',
  'auto-runner': 'autoRunner',
  'precision-platformer': 'precisionPlatformer',
  'climbing-game': 'climbingGame',
};

interface Target {
  readonly id: string;
  readonly gameId: string;
  readonly gamePath: string;
  readonly specModule: string;
}

function targets(filter: readonly string[]): Target[] {
  const unknown = filter.filter((id) => !(id in COMPLETION_SPEC_MODULES));
  if (unknown.length > 0) {
    throw new Error(`Unknown completion journey id(s): ${unknown.join(', ')}. Known: ${Object.keys(COMPLETION_SPEC_MODULES).join(', ')}`);
  }
  return Object.entries(COMPLETION_SPEC_MODULES)
    .filter(([id]) => filter.length === 0 || filter.includes(id))
    .map(([id, specModule]) => {
      const gameId = `final-${id}`.slice(0, 60);
      return { id, gameId, gamePath: path.join(GAMES_ROOT, gameId), specModule };
    });
}

function generate(target: Target): void {
  const preset = PRESETS.find((p) => p.id === target.id);
  if (!preset) throw new Error(`No preset ${target.id}`);
  rmSync(target.gamePath, { recursive: true, force: true });
  writeGameFiles(buildGameFiles(target.gameId, preset), target.gamePath);
}

function build(target: Target): { ok: boolean; detail: string } {
  const tscBin = path.join(REPO_ROOT, 'node_modules', '.bin', 'tsc');
  const tsc = spawnSync(tscBin, ['-p', 'tsconfig.json', '--noEmit'], { cwd: target.gamePath, encoding: 'utf8' });
  if (tsc.status !== 0) return { ok: false, detail: `tsc: ${(tsc.stdout || tsc.stderr).trim()}` };
  const viteBin = path.join(REPO_ROOT, 'node_modules', '.bin', 'vite');
  const result = spawnSync(viteBin, ['build'], { cwd: target.gamePath, encoding: 'utf8' });
  const ok = result.status === 0 && existsSync(path.join(target.gamePath, 'dist', 'index.html'));
  return { ok, detail: ok ? '' : `vite: ${(result.stderr || result.stdout || `exit ${result.status}`).trim()}` };
}

async function runTarget(target: Target): Promise<{ id: string; ok: boolean; detail: string }> {
  generate(target);
  try {
    const built = build(target);
    if (!built.ok) return { id: target.id, ok: false, detail: `build failed: ${built.detail}` };
    const { run } = (await import(`../../packages/qa/completion-specs/${target.specModule}.ts`)) as { run: Parameters<typeof runSmoke>[0]['run'] };
    const result = await runSmoke({ id: target.id, buildDir: path.join(target.gamePath, 'dist'), run });
    const detail = result.passed
      ? 'passed'
      : [
          result.failureReason ? `failed: ${result.failureReason}` : 'failed',
          `consoleErrors=${result.consoleErrors.length}`,
          `externalRequests=${result.externalRequests.length}`,
          result.consoleErrors.length > 0 ? `firstConsoleError=${result.consoleErrors[0]}` : '',
          `details=${JSON.stringify(result.details)}`,
        ]
          .filter(Boolean)
          .join(' ');
    return { id: target.id, ok: result.passed, detail };
  } finally {
    if (!process.env.SW2D_KEEP_COMPLETION_GAMES) rmSync(target.gamePath, { recursive: true, force: true });
  }
}

async function main(): Promise<number> {
  if (!findSystemChrome()) {
    console.error('No system Chrome found. Completion journeys cannot run - see `npm run sw2d -- doctor`.');
    return 1;
  }
  await ensureWorkspaceInstalled();
  const list = targets(process.argv.slice(2));
  const results: { id: string; ok: boolean; detail: string }[] = [];
  for (const target of list) {
    process.stdout.write(`Generating, building and playing ${target.id} (${target.gameId})...\n`);
    results.push(await runTarget(target));
    console.log(`[${results.at(-1)!.ok ? 'PASS' : 'FAIL'}] ${target.id}${results.at(-1)!.ok ? '' : ` - ${results.at(-1)!.detail}`}`);
  }
  console.log('\n--- completion journey summary ---');
  for (const r of results) console.log(`[${r.ok ? 'PASS' : 'FAIL'}] ${r.id}${r.ok ? '' : ` - ${r.detail.split('\n')[0]}`}`);
  const failed = results.filter((r) => !r.ok);
  console.log(`\n${results.length - failed.length}/${results.length} freshly generated games passed their completion journey.`);
  return failed.length === 0 ? 0 : 1;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main()
    .then((code) => {
      process.exitCode = code;
    })
    .catch((error: unknown) => {
      console.error(error);
      process.exitCode = 1;
    });
}
