import type { PresetDefinition } from '@sw2d/contracts';

function packLine(label: string, packIds: readonly string[]): string {
  return packIds.length > 0 ? `${label}: ${packIds.join(', ')}` : `${label}: (none)`;
}

const CODE = '```';
const TICK = '`';

function code(text: string): string {
  return TICK + text + TICK;
}

function codeBlock(lang: string, lines: readonly string[]): string {
  return [`${CODE}${lang}`, ...lines, CODE].join('\n');
}

/**
 * The generated README (MASTER_PROJECT.md section 23/26). Explains the
 * factory's own boundary in terms of this specific game's files, so a human
 * reading only this file - never MASTER_PROJECT.md - knows what is safe to
 * edit.
 */
export function generateReadme(gameId: string, displayName: string, preset: PresetDefinition): string {
  const requiredPacks = preset.requiredSystemPacks.map((s) => s.packId);
  const optionalPacks = preset.optionalSystemPacks.map((s) => s.packId);
  const limitations = preset.knownLimitations.length > 0 ? preset.knownLimitations.map((l) => `- ${l}`).join('\n') : '- (none stated)';

  const lines: string[] = [
    `# ${displayName}`,
    '',
    `Generated by ${code(`npm run sw2d -- new ${gameId} --preset ${preset.id}`)} from the ${code(preset.id)} preset`,
    `(family: ${preset.family}). This is a **recipe**, not a finished game - see "Known preset`,
    'limitations" below for what is deliberately not implemented yet.',
    '',
    '## How to run',
    '',
    codeBlock('bash', [`npm --workspace ${gameId} run dev`]),
    '',
    '## How to validate',
    '',
    codeBlock('bash', [`npm run sw2d -- validate ${gameId}`]),
    '',
    'Runs manifest/content schema validation, TypeScript, this game\'s tests, a production build,',
    'and (when a real browser is available) a focused smoke journey.',
    '',
    '## How to build',
    '',
    codeBlock('bash', [`npm run sw2d -- build ${gameId}`]),
    '',
    `Produces ${code(`games/${gameId}/dist/`)} - a self-contained static build with no required external`,
    'network request.',
    '',
    '## How to pack',
    '',
    codeBlock('bash', [`npm run sw2d -- pack ${gameId}`]),
    '',
    `Produces ${code(`games/${gameId}/pack/`)} - the same build, with source/tests/node_modules excluded,`,
    'ready to serve from any static file host.',
    '',
    '## Where normal game content lives',
    '',
    codeBlock('text', [
      'NORMAL GAME WORK              FACTORY/RUNTIME WORK (do not edit from here)',
      'content/**                    packages/contracts/**',
      'public/**                     packages/runtime/**',
      'themes/**                     shared system packs (packages/packs/**)',
      'src/game-specific/**          shared controllers (packages/runtime/src/controllers/**)',
    ]),
    '',
    `Edit ${code('content/game.json')} (manifest, packs, bindings/accessibility defaults),`,
    `${code('content/tuning.json')} (movement tuning - really read by this game's shell pack, not`,
    `decorative), ${code('content/themes/**')} (presentation), and ${code('src/game-specific/**')}`,
    "(this game's own mechanics) freely. This game consumes the factory's reusable packages as",
    'local workspace dependencies; it never copies their source.',
    '',
    `${code('src/game-specific/packConfig.ts')} is where packs that declare ${code("configSource: 'code'")} get`,
    'their configuration - config that carries functions, which `content/game.json` cannot express',
    `(${code('sw2d.puzzle')} is the one such pack today). If this preset selects one, that file ships`,
    'with a small working placeholder to replace. Every other pack is configured as JSON in',
    `${code('content/game.json')}.`,
    '',
    '## Composition',
    '',
    `- Controller family/families: ${preset.controllerFamilies.join(', ')}`,
    `- ${packLine('Required packs (enabled by default)', requiredPacks)}`,
    `- ${packLine("Optional packs (available, not enabled by default - add to content/game.json's systemPacks to use)", optionalPacks)}`,
    `- Content roles this preset expects: ${preset.requiredContentRoles.join(', ')}`,
    '',
    '## Known preset limitations',
    '',
    limitations,
    '',
    '## How to add a level',
    '',
    codeBlock('bash', [`npm run sw2d -- add-level ${gameId} <level-id>`]),
    '',
    `Writes ${code('content/levels/<level-id>.json')} - a valid Tiled JSON export using the Phase 6`,
    'object-class subset (PlayerSpawn, Checkpoint, Collectible, Hazard, Exit, Solid). Reference it',
    `as a content document named ${code('levels/<level-id>')}.`,
    '',
    '## How to add a theme',
    '',
    codeBlock('bash', [`npm run sw2d -- add-theme ${gameId} <theme-id>`]),
    '',
    `Writes ${code('content/themes/<theme-id>/theme.json')} - a valid local ThemeManifest. Swapping`,
    `which theme ${code('src/content.ts')} loads changes presentation only; it never changes gameplay`,
    'data.',
    '',
  ];

  return lines.join('\n');
}
