import { footprintRect, rectContains, rectsOverlap, type Footprint, type Point, type Rect } from './geometry.ts';
import type { NavCellRef } from './navigation.ts';
export const CONSTRUCTION_CAPABILITY_ID = 'simulation.construction';
export interface BuildableDefinition { readonly id: string; readonly footprint: Footprint; readonly cost: number; readonly durationMs: number; readonly resultArchetype: string; readonly blocksNavigation?: boolean; readonly refundRatio?: number; }
export interface ConstructionZone extends Rect { readonly id: string; readonly kind: 'buildable' | 'blocked'; }
export interface RequiredNavigationRoute { readonly from: NavCellRef; readonly to: NavCellRef; }
export interface ConstructionNavigation { readonly gridId: string; readonly requiredRoutes: readonly RequiredNavigationRoute[]; }
export interface ConstructionDocument { readonly schemaVersion: 1; readonly startingResources: number; readonly buildables: readonly BuildableDefinition[]; readonly zones: readonly ConstructionZone[]; readonly navigation?: ConstructionNavigation; }
export type ConstructionPhase = 'blueprint' | 'building' | 'complete' | 'cancelled';
export interface ConstructionSite { readonly id: string; readonly buildableId: string; readonly position: Point; readonly phase: ConstructionPhase; readonly progressMs: number; readonly workerId: string | null; readonly paidCost: number; }
export type ConstructionResult = { readonly ok: true; readonly siteId?: string } | { readonly ok: false; readonly reason: 'unknown-buildable' | 'outside-zone' | 'blocked-zone' | 'overlap' | 'insufficient-resources' | 'route-blocked' | 'unknown-site' | 'wrong-phase' };
export interface ConstructionService { resources(): number; sites(): readonly ConstructionSite[]; preview(buildableId: string, position: Point): ConstructionResult; place(buildableId: string, position: Point): ConstructionResult; assign(siteId: string, workerId: string): ConstructionResult; advance(deltaMs: number): void; cancel(siteId: string): ConstructionResult; deconstruct(siteId: string): ConstructionResult; }
export function validateConstructionDocument(doc: ConstructionDocument): void { const ids = new Set<string>(); for (const b of doc.buildables) { if (!b.id || ids.has(b.id) || b.cost < 0 || !(b.durationMs > 0) || !(b.footprint.width > 0) || !(b.footprint.height > 0)) throw new Error(`Invalid buildable "${b.id}".`); ids.add(b.id); } }
export function placementReason(doc: ConstructionDocument, sites: readonly ConstructionSite[], buildable: BuildableDefinition, position: Point, routeIntact: (rect: Rect) => boolean): Exclude<ConstructionResult, { ok: true }>['reason'] | null { const rect = footprintRect(position, buildable.footprint); const zones = doc.zones; if (!zones.some((zone) => zone.kind === 'buildable' && rectContains(zone, rect))) return 'outside-zone'; if (zones.some((zone) => zone.kind === 'blocked' && rectsOverlap(zone, rect))) return 'blocked-zone'; if (sites.some((site) => site.phase !== 'cancelled' && rectsOverlap(rect, footprintRect(site.position, doc.buildables.find((b) => b.id === site.buildableId)!.footprint)))) return 'overlap'; if (buildable.blocksNavigation && !routeIntact(rect)) return 'route-blocked'; return null; }
