import type { AutoCombatArchetype, AutoCombatDocument, AutoCombatEvent, AutoCombatService, AutoCombatUnitState, GameContext, SystemPackDefinition, WeaponsService } from '@sw2d/contracts';
import { moveToward, selectAutoCombatTarget, validateAutoCombatDocument } from '@sw2d/contracts';
import { registerSchema } from '@sw2d/schemas';
import { CAPABILITY_IDS, PACK_IDS } from '../ids.ts';
import type { CombatService } from '../combat/combatPack.ts';
import autoCombatConfigSchema from '../../schemas/auto-combat-config.schema.json' with { type: 'json' };

export const AUTO_COMBAT_CONFIG_SCHEMA_ID = autoCombatConfigSchema.$id;
registerSchema(autoCombatConfigSchema);
export interface AutoCombatConfig { readonly documentName?: string; }
export class MissingAutoCombatDocumentError extends Error { constructor(name: string) { super(`sw2d.auto-combat requires content/${name}.json.`); this.name = 'MissingAutoCombatDocumentError'; } }

class AutoCombatServiceImpl implements AutoCombatService {
  readonly #archetypes = new Map<string, AutoCombatArchetype>(); readonly #slots = new Map<string, AutoCombatDocument['slots'][number]>(); readonly #combat: CombatService; readonly #weapons: WeaponsService; readonly #units = new Map<string, AutoCombatUnitState>(); readonly #events: AutoCombatEvent[] = [];
  #phase: ReturnType<AutoCombatService['phase']> = 'deploy'; #winner: string | null = null; #clock = 0; #nextId = 1;
  constructor(doc: AutoCombatDocument, combat: CombatService, weapons: WeaponsService) { validateAutoCombatDocument(doc); this.#combat = combat; this.#weapons = weapons; for (const a of doc.archetypes) this.#archetypes.set(a.id, a); for (const s of doc.slots) this.#slots.set(s.id, s); }
  phase() { return this.#phase; } units() { return [...this.#units.values()].sort((a,b) => a.instanceId.localeCompare(b.instanceId)); } winner() { return this.#winner; }
  deploy(archetypeId: string, slotId: string) { if (this.#phase !== 'deploy' && this.#phase !== 'ready') return { ok: false as const, reason: 'round-started' as const }; const archetype = this.#archetypes.get(archetypeId); if (!archetype) return { ok: false as const, reason: 'unknown-archetype' as const }; const slot = this.#slots.get(slotId); if (!slot) return { ok: false as const, reason: 'unknown-slot' as const }; if (slot.teamId !== archetype.teamId) return { ok: false as const, reason: 'wrong-team' as const }; if (this.units().some((u) => u.x === slot.x && u.y === slot.y)) return { ok: false as const, reason: 'occupied-slot' as const }; const instanceId = `unit-${this.#nextId++}`; this.#units.set(instanceId, { instanceId, archetypeId, teamId: archetype.teamId, x: slot.x, y: slot.y, phase: 'acquire', targetId: null, nextReassessAtMs: 0 }); this.#combat.register(instanceId, archetype.maxHealth); this.#weapons.equip(instanceId, archetype.weaponId); this.#events.push({ kind: 'deployed', instanceId, slotId }); this.#phase = 'ready'; return { ok: true as const, instanceId }; }
  start() { if (this.#phase !== 'ready' || new Set(this.units().map((unit) => unit.teamId)).size < 2) return false; this.#phase = 'battle'; return true; }
  update(deltaMs: number) { if (this.#phase !== 'battle') return; this.#clock += Math.max(0, deltaMs); for (const state of this.units()) { const archetype = this.#archetypes.get(state.archetypeId)!; if (!this.#combat.has(state.instanceId) || this.#combat.get(state.instanceId).current <= 0) { if (state.phase !== 'dead') this.#events.push({ kind: 'defeated', instanceId: state.instanceId }); this.#units.set(state.instanceId, { ...state, phase: 'dead' }); continue; } const enemies = this.units().filter((other) => other.teamId !== state.teamId && this.#combat.has(other.instanceId) && this.#combat.get(other.instanceId).current > 0).map((other) => ({ id: other.instanceId, teamId: other.teamId, x: other.x, y: other.y, health: this.#combat.get(other.instanceId).current, threat: this.#archetypes.get(other.archetypeId)!.threat ?? 0, roleTags: this.#archetypes.get(other.archetypeId)!.roleTags ?? [] })); let targetId = state.targetId; if (this.#clock >= state.nextReassessAtMs || !enemies.some((enemy) => enemy.id === targetId)) { targetId = selectAutoCombatTarget(archetype.targetPolicy, archetype.roleTags?.[0], state, enemies)?.id ?? null; this.#events.push({ kind: 'targeted', instanceId: state.instanceId, targetId }); } const target = enemies.find((enemy) => enemy.id === targetId); if (!target) { this.#units.set(state.instanceId, { ...state, targetId: null, phase: 'complete', nextReassessAtMs: this.#clock + (archetype.reassessMs ?? 250) }); continue; } const distance = Math.hypot(target.x - state.x, target.y - state.y); if (distance > archetype.range) { const moved = moveToward(state, target, archetype.moveSpeed * deltaMs / 1000); this.#units.set(state.instanceId, { ...state, ...moved, targetId, phase: 'move', nextReassessAtMs: this.#clock + (archetype.reassessMs ?? 250) }); continue; } const fired = this.#weapons.tryFire({ ownerId: state.instanceId, originX: state.x, originY: state.y, dirX: target.x - state.x, dirY: target.y - state.y, nowMs: this.#clock }); for (const spawn of fired.spawns) this.#combat.damage(target.id, spawn.damage, this.#clock); this.#units.set(state.instanceId, { ...state, targetId, phase: 'engage', nextReassessAtMs: this.#clock + (archetype.reassessMs ?? 250) }); }
    const aliveTeams = new Set(this.units().filter((u) => this.#combat.has(u.instanceId) && this.#combat.get(u.instanceId).current > 0).map((u) => u.teamId)); if (aliveTeams.size <= 1) { this.#winner = aliveTeams.values().next().value ?? null; this.#phase = 'resolve'; this.#events.push({ kind: 'round-complete', winner: this.#winner }); }
  }
  reset() { for (const unit of this.units()) { this.#combat.remove(unit.instanceId); this.#weapons.unequip(unit.instanceId); } this.#units.clear(); this.#events.length = 0; this.#phase = 'deploy'; this.#winner = null; this.#clock = 0; this.#nextId = 1; }
  drainEvents() { return this.#events.splice(0); }
}

export const autoCombatPack: SystemPackDefinition<AutoCombatConfig, GameContext> = { id: PACK_IDS.autoCombat, version: '0.1.0', provides: [CAPABILITY_IDS.autoCombat], dependencies: [CAPABILITY_IDS.combat, CAPABILITY_IDS.weapons], configSchemaId: AUTO_COMBAT_CONFIG_SCHEMA_ID, install(context, config) { const name = config?.documentName ?? 'auto-combat'; const doc = context.content.data[name]?.value as AutoCombatDocument | undefined; if (!doc) throw new MissingAutoCombatDocumentError(name); const service = new AutoCombatServiceImpl(doc, context.capabilities.require<CombatService>(CAPABILITY_IDS.combat), context.capabilities.require<WeaponsService>(CAPABILITY_IDS.weapons)); const handle = context.capabilities.provide(CAPABILITY_IDS.autoCombat, service); return { id: PACK_IDS.autoCombat, update(deltaMs) { service.update(deltaMs); }, dispose() { handle.dispose(); } }; } };
export { AutoCombatServiceImpl };
