import { describe, expect, it } from 'vitest';
import type { ConstructionService } from '@sw2d/contracts';
import { constructionPack } from '../src/construction/constructionPack.ts';
import { navigationPack } from '../src/navigation/navigationPack.ts';
import { createFakeGameContext } from './testSupport.ts';

const doc = { schemaVersion: 1 as const, startingResources: 20, buildables: [{ id: 'hut', footprint: { width: 2, height: 2 }, cost: 10, durationMs: 100, resultArchetype: 'hut', refundRatio: 0.5 }], zones: [{ id: 'yard', kind: 'buildable' as const, x: 0, y: 0, width: 20, height: 20 }, { id: 'rock', kind: 'blocked' as const, x: 8, y: 8, width: 2, height: 2 }] };
function service() { const base = createFakeGameContext(); const game = { ...base, content: { ...base.content, data: { construction: { schemaId: 'construction', valid: true as const, value: doc } } } }; constructionPack.install(game, undefined); return game.capabilities.require<ConstructionService>('simulation.construction'); }
describe('construction pack', () => {
  it('rejects invalid placement, deducts once, builds and deconstructs with refund', () => { const s = service(); expect(s.place('hut', { x: 30, y: 30 })).toMatchObject({ ok: false, reason: 'outside-zone' }); const placed = s.place('hut', { x: 3, y: 3 }); expect(placed.ok).toBe(true); expect(s.resources()).toBe(10); expect(s.place('hut', { x: 3, y: 3 })).toMatchObject({ ok: false, reason: 'overlap' }); const id = placed.ok ? placed.siteId! : ''; s.assign(id, 'worker'); s.advance(100); expect(s.sites()[0]?.phase).toBe('complete'); expect(s.deconstruct(id).ok).toBe(true); expect(s.resources()).toBe(15); });
  it('cancels a blueprint without duplicating a refund', () => { const s = service(); const placed = s.place('hut', { x: 3, y: 3 }); const id = placed.ok ? placed.siteId! : ''; expect(s.cancel(id).ok).toBe(true); expect(s.resources()).toBe(15); expect(s.cancel(id)).toMatchObject({ ok: false, reason: 'wrong-phase' }); });
  it('rolls back its temporary navigation blocker after rejecting a trapped route', () => { const base = createFakeGameContext(); const blocked = { ...doc, buildables: [{ ...doc.buildables[0]!, blocksNavigation: true }], navigation: { gridId: 'roads', requiredRoutes: [{ from: { col: 0, row: 0 }, to: { col: 2, row: 0 } }] } }; const game = { ...base, content: { ...base.content, data: { construction: { schemaId: 'construction', valid: true as const, value: blocked } } } }; navigationPack.install(game, undefined); const nav = game.capabilities.require<any>('world.navigation'); const grid = nav.defineGrid('roads', { cols: 3, rows: 1, cellSize: 10 }); constructionPack.install(game, undefined); const s = game.capabilities.require<ConstructionService>('simulation.construction'); expect(s.place('hut', { x: 10, y: 3 })).toMatchObject({ ok: false, reason: 'route-blocked' }); expect(grid.isWalkable(1, 0)).toBe(true); });
});
