import type { FarmingDocument, FarmingPlot, FarmingService, GameContext, InstalledSystemPack, SystemPackDefinition } from '@sw2d/contracts';
import { validateFarmingDocument } from '@sw2d/contracts';
import { CAPABILITY_IDS, PACK_IDS } from '../ids.ts';
import type { ItemsService } from '../items/itemsPack.ts';

const SEASONS = ['spring', 'summer', 'autumn', 'winter'] as const;
class FarmingServiceImpl implements FarmingService {
  readonly #doc: FarmingDocument; readonly #items: ItemsService; readonly #plots = new Map<string, FarmingPlot>(); #day = 1;
  constructor(doc: FarmingDocument, items: ItemsService) { validateFarmingDocument(doc); this.#doc = doc; this.#items = items; for (const id of doc.plots) this.#plots.set(id, { id, phase: 'empty', cropId: null, stageIndex: 0, progressDays: 0, watered: false }); }
  calendar() { const index = Math.floor((this.#day - 1) / this.#doc.daysPerSeason) % SEASONS.length; return { day: this.#day, season: SEASONS[index]!, dayInSeason: ((this.#day - 1) % this.#doc.daysPerSeason) + 1 }; }
  plots() { return [...this.#plots.values()].sort((a, b) => a.id.localeCompare(b.id)); }
  till(id: string) { const p = this.#plots.get(id); if (!p) return fail('unknown-plot'); if (p.phase !== 'empty') return fail('wrong-phase'); this.#set({ ...p, phase: 'tilled' }); return ok(); }
  plant(id: string, cropId: string) { const p = this.#plots.get(id); if (!p) return fail('unknown-plot'); if (p.phase !== 'tilled') return fail('wrong-phase'); const crop = this.#doc.crops.find((item) => item.id === cropId); if (!crop) return fail('unknown-crop'); if (!crop.validSeasons.includes(this.calendar().season)) return fail('invalid-season'); if (!this.#items.canConsume(crop.seedItemId)) return fail('missing-seed'); this.#items.consume(crop.seedItemId); this.#set({ ...p, phase: 'planted', cropId, stageIndex: 0, progressDays: 0, watered: false }); return ok(); }
  water(id: string) { const p = this.#plots.get(id); if (!p) return fail('unknown-plot'); if (p.phase !== 'planted' && p.phase !== 'growing') return fail('wrong-phase'); this.#set({ ...p, watered: true }); return ok(); }
  harvest(id: string) { const p = this.#plots.get(id); if (!p) return fail('unknown-plot'); if (p.phase !== 'harvestable' || !p.cropId) return fail('not-ready'); const crop = this.#crop(p.cropId); for (const out of crop.harvestItems) this.#items.grant(out.itemId, out.quantity); const stage = crop.regrowStage; this.#set(stage === undefined ? { ...p, phase: 'tilled', cropId: null, stageIndex: 0, progressDays: 0, watered: false } : { ...p, phase: 'growing', stageIndex: stage, progressDays: 0, watered: false }); return ok(); }
  clear(id: string) { const p = this.#plots.get(id); if (!p) return fail('unknown-plot'); if (p.phase === 'empty') return fail('wrong-phase'); this.#set({ ...p, phase: 'empty', cropId: null, stageIndex: 0, progressDays: 0, watered: false }); return ok(); }
  advanceDays(days: number) { for (let i = 0; i < Math.max(0, Math.floor(days)); i++) { this.#day++; for (const plot of this.plots()) { if (!plot.cropId || (plot.phase !== 'planted' && plot.phase !== 'growing')) continue; const crop = this.#crop(plot.cropId); if (crop.requiresWater && !plot.watered) continue; const stage = crop.growthStages[plot.stageIndex]!; const progress = plot.progressDays + 1; if (progress >= stage.durationDays) { const next = plot.stageIndex + 1; this.#set(next >= crop.growthStages.length ? { ...plot, phase: 'harvestable', progressDays: progress, watered: false } : { ...plot, phase: 'growing', stageIndex: next, progressDays: 0, watered: false }); } else this.#set({ ...plot, phase: 'growing', progressDays: progress, watered: false }); } } }
  #crop(id: string) { return this.#doc.crops.find((crop) => crop.id === id)!; } #set(plot: FarmingPlot) { this.#plots.set(plot.id, plot); }
}
const ok = (): { readonly ok: true } => ({ ok: true }); const fail = (reason: Exclude<ReturnType<FarmingService['till']>, { ok: true }>['reason']): { readonly ok: false; readonly reason: typeof reason } => ({ ok: false, reason });
export const farmingPack: SystemPackDefinition<undefined, GameContext> = { id: PACK_IDS.farming, version: '0.1.0', provides: [CAPABILITY_IDS.farming], dependencies: [CAPABILITY_IDS.items], install(context): InstalledSystemPack { const doc = context.content.data.farming?.value as FarmingDocument | undefined; if (!doc) throw new Error('sw2d.farming requires content/farming.json.'); const handle = context.capabilities.provide(CAPABILITY_IDS.farming, new FarmingServiceImpl(doc, context.capabilities.require<ItemsService>(CAPABILITY_IDS.items))); return { id: PACK_IDS.farming, dispose: () => handle.dispose() }; } };
export { FarmingServiceImpl }; export type { FarmingService } from '@sw2d/contracts';
