import { plan, type ExplicitStarterKitPlan } from './types.ts';

export const NARRATIVEEXPLORATION_SCAFFOLD_PLANS = {
  'exploration-game': plan('Move through a compact authored space, discover several points of interest, and reach a completion marker after exploring them.', 'twin-stick-shooter', ['player', 'background', 'pickup', 'checkpoint', 'exit', 'ui.panel'], ['top-down exploration movement works', 'points of interest can be discovered', 'completion reflects discovery progress'], 2, ['Keep the world authored; no world-map graph system.']),
  'visual-novel': plan('Advance dialogue, make at least one branching choice, and reach one of two explicit endings.', 'idle-incremental', ['player', 'background', 'ui.panel', 'ui.button', 'pickup'], ['dialogue advances through user input', 'choice changes branch state', 'ending reflects the chosen branch'], 1, ['A bounded game-specific dialogue renderer is allowed; do not claim a reusable VN framework.']),
  'point-and-click': plan('Move a visible cursor between hotspots, inspect/combine a small clue set, and unlock an exit interaction.', 'idle-incremental', ['player', 'background', 'pickup', 'ui.cursor', 'ui.panel'], ['hotspot selection is visible', 'clue/inventory state changes', 'exit is gated by puzzle/clue state'], 3, ['Provide keyboard/grid cursor fallback if spatial pointer is unavailable; keep any direct pointer handling game-specific and documented.']),
  'interactive-fiction-hybrid': plan('Navigate a short text-driven scene with menu verbs/choices, change story state, and reach a branching outcome.', 'idle-incremental', ['player', 'background', 'ui.panel', 'ui.button', 'pickup'], ['text/choice progression works', 'one stateful verb/choice changes later options', 'outcome is branch-dependent'], 3, ['Use bounded menu verbs; no parser or scripting language.']),
  'investigation-game': plan('Explore a small scene, collect clues, make one deduction from the evidence set, and unlock the case conclusion.', 'twin-stick-shooter', ['player', 'background', 'pickup', 'ui.cursor', 'ui.panel', 'exit'], ['clues can be collected', 'deduction state depends on required clues', 'case conclusion unlocks only after valid deduction'], 3, ['Evidence linking may be a bounded UI list/grid, not a generalized evidence-board system.']),
  'museum-exhibit': plan('Walk through a small exhibit space, inspect several exhibits, and complete the visit after viewing a required set.', 'twin-stick-shooter', ['player', 'background', 'pickup', 'ui.panel', 'ui.cursor', 'exit'], ['movement through exhibit space works', 'exhibit interaction opens content/presentation', 'visit completion tracks viewed exhibits'], 2, ['Use game-specific exhibit panels; do not create a general codex framework.']),
  'escape-room': plan('Inspect a compact room, solve two linked puzzles, and unlock the final exit.', 'sokoban', ['player', 'background', 'pickup', 'ui.cursor', 'ui.panel', 'exit'], ['two puzzle states are independently manipulable', 'second/final state depends on prior progress', 'exit stays locked until solved'], 3, ['Use bounded authored puzzle logic and cursor fallback; no escape-room grammar.']),
} as const satisfies Readonly<Record<string, ExplicitStarterKitPlan>>;
