import { plan, type ExplicitStarterKitPlan } from './types.ts';

export const PARTYTOYWEIRD_SCAFFOLD_PLANS = {
  'microgame-collection': plan('Play three very short deterministic microgames in sequence and finish with a combined score/result.', 'idle-incremental', ['player', 'background', 'ui.panel', 'ui.button', 'ui.cursor', 'particle'], ['at least three distinct microgame rules exist', 'scheduler advances between them', 'combined result is shown'], 3, ['Implement a tiny local scheduler; do not generalize into a reusable microgame framework.']),
  'local-party-game': plan('Run a single-device pass-and-play or alternating-turn mini contest with two player slots and a clear winner.', 'idle-incremental', ['player', 'background', 'ui.panel', 'ui.button'], ['two player identities/scores are tracked', 'turn/control alternates on one device', 'winner is resolved'], 3, ['Do not imply simultaneous multiplayer or multi-device routing; use pass-and-play/alternating turns.']),
  'physics-toy': plan('Interact with a small sandbox of objects using a bounded push/spawn/trigger control set and observe persistent motion.', 'sokoban', ['player', 'background', 'platform', 'pickup', 'ui.cursor', 'particle'], ['user interaction changes object state', 'objects visibly move/collide', 'reset restores deterministic initial state'], 3, ['Only implement the local toy physics needed; no shared advanced physics system.']),
  'virtual-pet': plan('Care for a character through several actions while needs change, then reach a short happy/healthy target.', 'idle-incremental', ['player', 'background', 'pickup', 'ui.panel', 'ui.button'], ['multiple needs are tracked', 'care actions change needs/feedback', 'target wellbeing state is reachable'], 3, ['Bounded local state machine only; no shared creature simulation.']),
  'dress-up-character-toy': plan('Select wardrobe pieces from a bounded menu, apply them to a character presentation, and save/reset the look in-session.', 'idle-incremental', ['player', 'background', 'pickup', 'ui.panel', 'ui.button', 'ui.cursor'], ['wardrobe selection changes visible state', 'multiple slots/categories can be changed', 'reset restores starting look'], 3, ['Use click/menu selection rather than requiring drag/drop; no attachment framework.']),
  'sandbox-playground': plan('Place or toggle a small set of playground objects, interact with them, and reset the scene.', 'sokoban', ['player', 'background', 'platform', 'pickup', 'ui.cursor', 'particle'], ['object placement/toggle changes scene state', 'at least two object interactions differ', 'reset restores authored baseline'], 3, ['This is a bounded toy, not a generalized level editor.']),
  'drawing-game': plan('Move a cursor/brush across a bounded canvas grid, leave visible marks, and complete/reset a simple drawing task.', 'idle-incremental', ['player', 'background', 'ui.cursor', 'ui.panel', 'ui.button'], ['brush/cursor movement is visible', 'drawing changes persistent canvas state', 'clear/reset works'], 3, ['Use grid/keyboard cursor if continuous spatial drawing is unavailable; do not add a shared pointer-drawing service.']),
  'fishing-game': plan('Start a cast, react during a bite/tension sequence, land a fish, and complete a short catch target.', 'idle-incremental', ['player', 'background', 'pickup', 'ui.panel', 'ui.button', 'particle'], ['cast/bite/tension states progress visibly', 'player timing affects catch success', 'caught fish/score changes'], 3, ['Keep casting/tension/fish behavior as a compact local state machine.']),
  'cooking-game': plan('Complete a short ordered recipe by selecting ingredients/actions in sequence and finish with a scored dish result.', 'idle-incremental', ['player', 'background', 'pickup', 'ui.panel', 'ui.button', 'particle'], ['recipe step sequence is enforced', 'wrong/right actions change state/feedback', 'finished dish/result is explicit'], 3, ['Implement one or two authored recipes; no reusable cooking system.']),
  'photography-game': plan('Explore a small scene, frame/select a target with a bounded camera cursor, capture it, and score the photo.', 'twin-stick-shooter', ['player', 'background', 'enemy', 'ui.cursor', 'ui.panel', 'particle'], ['movement/exploration works', 'camera/target selection state is visible', 'capture produces a deterministic score/result'], 3, ['Use a bounded reticle/framing heuristic; no generalized camera/photo system or reusable spatial pointer requirement.']),
} as const satisfies Readonly<Record<string, ExplicitStarterKitPlan>>;
