import { plan, type ExplicitStarterKitPlan } from './types.ts';

export const PLATFORMING_SCAFFOLD_PLANS = {
  'traditional-platformer': plan('Reach the exit by running and jumping through a compact obstacle course while collecting optional pickups.', 'chase-platformer', ['player', 'background', 'platform', 'pickup', 'hazard', 'checkpoint', 'exit'], ['player can move and jump through a designed level', 'at least one pickup can be collected', 'hazard/checkpoint/exit interactions are observable'], 1, ['Use chase-platformer as the structural base, removing chase pressure and keeping the level-driven world.']),
  'endless-runner': plan('Survive an auto-scrolling run by jumping hazards and collecting score pickups until the run ends.', 'chase-platformer', ['player', 'background', 'platform', 'pickup', 'hazard'], ['horizontal run advances without manual movement input', 'jump avoids at least one hazard', 'score/distance increases during a run'], 2, ['Keep endless sequencing bounded and deterministic in game-specific code; do not introduce a shared procedural-generation subsystem.']),
  'precision-platformer': plan('Cross a short high-precision platforming gauntlet with tight jumps, hazards, checkpoints, and a finish gate.', 'chase-platformer', ['player', 'background', 'platform', 'hazard', 'checkpoint', 'exit'], ['movement/jump tuning is visibly tighter than the traditional kit', 'checkpoint respawn works', 'finish is reachable without placeholder-only mechanics'], 2, ['Reuse platform controller intent; precision feel belongs in game-specific tuning/policy.']),
  'metroidvania': plan('Explore a small interconnected level, acquire one traversal ability, backtrack through a previously blocked route, and reach the exit.', 'chase-platformer', ['player', 'background', 'platform', 'pickup', 'hazard', 'checkpoint', 'exit'], ['ability pickup changes traversal capability', 'a gate/route is inaccessible before the ability and accessible after', 'progression state survives normal scene flow'], 1, ['Keep the world graph deliberately small and authored; do not invent a reusable map/world-graph engine.']),
  'puzzle-platformer': plan('Move through a platforming room where opening the exit requires solving a discrete environmental puzzle.', 'chase-platformer', ['player', 'background', 'platform', 'pickup', 'hazard', 'exit', 'ui.cursor'], ['platform movement remains functional', 'one puzzle state must be changed deliberately', 'exit remains locked until puzzle condition is satisfied'], 2, ['Use existing puzzle foundations only; puzzle rules may remain bounded game-specific code.']),
  'auto-runner': plan('Advance automatically through a short authored course while the player controls jump timing to avoid hazards and finish.', 'chase-platformer', ['player', 'background', 'platform', 'pickup', 'hazard', 'exit'], ['forward motion is automatic', 'jump timing changes success/failure', 'finish/outcome is observable'], 2, ['Do not add procedural generation; loop/recycle a bounded authored course if repetition is needed.']),
  'climbing-game': plan('Climb vertically between ledges, recover from falls at checkpoints, and reach a summit marker.', 'chase-platformer', ['player', 'background', 'platform', 'checkpoint', 'hazard', 'exit'], ['vertical progression is the primary spatial goal', 'fall/respawn or recovery is observable', 'summit completion is explicit'], 3, ['Implement climbing-specific feel locally without changing the shared platform controller.']),
  'grappling-platformer': plan('Cross a compact gap course using a bounded grapple mechanic plus normal movement to reach the exit.', 'chase-platformer', ['player', 'background', 'platform', 'hazard', 'checkpoint', 'exit', 'particle'], ['grapple visibly changes player trajectory', 'grapple has a bounded valid target/range model', 'course requires at least one grapple to finish'], 3, ['Keep grapple physics entirely game-specific; no shared grappling/rope subsystem may be introduced during starter-kit work.']),
  'collectathon-platformer': plan('Explore a platforming space, collect a visible quota of items, and unlock the exit after the quota is met.', 'chase-platformer', ['player', 'background', 'platform', 'pickup', 'hazard', 'checkpoint', 'exit'], ['multiple collectibles are tracked', 'exit is gated by collection progress', 'collection state is visible in debug/UI state'], 2, ['This can reuse much of chase-platformer after removing chase pressure and emphasizing collection.']),
} as const satisfies Readonly<Record<string, ExplicitStarterKitPlan>>;
