import { plan, type ExplicitStarterKitPlan } from './types.ts';

export const PUZZLEARCADE_SCAFFOLD_PLANS = {
  'match-puzzle': plan('Swap or select adjacent grid cells to create a match, clear pieces, and reach a score/clear target.', 'sokoban', ['player', 'background', 'pickup', 'ui.cursor', 'ui.panel'], ['grid selection is visible', 'a valid match changes board state', 'target score/clear condition completes the round'], 3, ['Use deterministic bounded board logic; no generalized match/cascade engine or drag requirement.']),
  'falling-block-puzzle': plan('Move and rotate falling blocks on a small board, clear at least one line, and continue until a bounded end state.', 'sokoban', ['player', 'background', 'platform', 'ui.panel'], ['piece falls on deterministic ticks', 'move/rotate changes placement', 'line clear and score/state change are observable'], 3, ['Keep falling-piece/line-clear logic game-specific.']),
  'breakout': plan('Move a paddle, bounce a ball, break a brick set, and complete the round when bricks are gone.', 'sokoban', ['player', 'background', 'enemy', 'pickup', 'particle'], ['paddle movement affects ball return', 'ball collision removes bricks', 'round ends when bricks are cleared or ball is lost'], 2, ['Implement bounded arcade ball/paddle physics locally.']),
  'pong': plan('Move a paddle against a simple opponent, exchange the ball, and score to a short win condition.', 'sokoban', ['player', 'background', 'enemy', 'ui.panel'], ['paddle movement works', 'ball bounces and crosses scoring boundaries', 'score reaches a bounded win condition'], 3, ['Single-player opponent is sufficient; do not invent multiplayer input routing.']),
  'physics-puzzle': plan('Trigger a small physics-like contraption to move an object into a goal using a bounded interaction set.', 'sokoban', ['player', 'background', 'platform', 'pickup', 'hazard', 'ui.cursor'], ['player can select/trigger a puzzle element', 'object motion/collision changes puzzle state', 'goal completion is explicit'], 3, ['Approximate only the physics needed for the authored puzzle; do not add an advanced shared physics engine.']),
  'maze-game': plan('Navigate a grid maze, collect an optional item, and reach the exit without crossing walls.', 'sokoban', ['player', 'background', 'platform', 'pickup', 'exit'], ['grid movement respects walls', 'maze has a reachable path', 'exit completion is explicit'], 2, ['Keep maze authored and deterministic.']),
  'rhythm-action': plan('Respond to a deterministic visual beat lane/timing sequence and finish with a scored accuracy result.', 'idle-incremental', ['player', 'background', 'ui.panel', 'ui.button', 'particle'], ['timing windows are deterministic and visible', 'input is judged against windows', 'round produces an accuracy/score result'], 3, ['Use a visual deterministic clock; do not claim audio-synchronized beat infrastructure.']),
  'reaction-timing': plan('Wait for a clear go signal, react once, measure response time, and complete a short multi-round result.', 'idle-incremental', ['player', 'background', 'ui.panel', 'ui.button'], ['false-start state is handled', 'reaction time is measured from deterministic signal state', 'summary result appears after bounded rounds'], 2, ['Keep it deterministic in tests by exposing state/debug rather than relying on wall-clock precision.']),
  'pinball-lite': plan('Launch a ball into a compact table, bounce from bumpers, score points, and end after a bounded number of drains.', 'sokoban', ['player', 'background', 'enemy', 'hazard', 'particle', 'ui.panel'], ['ball launch and collisions are visible', 'bumper interactions score', 'drain/lives create a bounded end state'], 3, ['Implement only table-local arcade physics; no shared advanced physics system.']),
} as const satisfies Readonly<Record<string, ExplicitStarterKitPlan>>;
