import { plan, type ExplicitStarterKitPlan } from './types.ts';

export const SHOOTER_SCAFFOLD_PLANS = {
  'horizontal-shmup': plan('Fly horizontally through a bounded encounter, shoot enemy targets, dodge hazards, and clear the stage.', 'twin-stick-shooter', ['player', 'background', 'enemy', 'pickup', 'hazard', 'particle', 'exit'], ['player firing creates visible projectiles/effects', 'enemies can be destroyed', 'stage clear condition is explicit'], 2, ['Keep projectile/firing implementation game-specific.']),
  'vertical-shmup': plan('Fly upward through a bounded shooter lane, destroy enemies, dodge fire/hazards, and clear the wave.', 'twin-stick-shooter', ['player', 'background', 'enemy', 'pickup', 'hazard', 'particle'], ['vertical movement and firing work', 'enemy wave can be cleared', 'player can take damage or fail'], 2, ['Use an authored bounded wave; no procedural enemy generator.']),
  'bullet-hell': plan('Survive a short dense but deterministic bullet pattern, damage the source enemy, and clear the encounter.', 'twin-stick-shooter', ['player', 'background', 'enemy', 'hazard', 'particle'], ['dense deterministic projectile pattern is visible', 'player collision/damage is reliable', 'encounter has a bounded completion state'], 1, ['Use bounded pooling/pattern code in the game-specific shell; do not turn it into a shared bullet engine.']),
  'asteroids-shooter': plan('Steer a ship with vehicle-like inertia intent, fire at drifting targets, survive collisions, and clear the field.', 'twin-stick-shooter', ['player', 'background', 'enemy', 'hazard', 'particle', 'pickup'], ['vehicle steering/throttle intent controls ship motion', 'projectiles destroy targets', 'collision or health state is observable'], 3, ['Approximate inertia locally; do not claim reusable rotational physics.']),
  'gallery-shooter': plan('Move a visible aim cursor between targets, fire to score hits, and clear a timed target set.', 'twin-stick-shooter', ['player', 'background', 'enemy', 'ui.cursor', 'particle'], ['cursor/target selection is visible', 'confirm/fire scores a hit on selected target', 'round ends after target/time condition'], 3, ['If spatial pointer coordinates are unavailable, provide an honest keyboard/grid cursor fallback rather than inventing reusable pointer capability.']),
  'run-and-gun': plan('Run and jump through a short side-view combat course, shoot enemies, and reach the exit.', 'chase-platformer', ['player', 'background', 'platform', 'enemy', 'hazard', 'pickup', 'particle', 'exit'], ['platform movement/jump works', 'player firing defeats at least one enemy', 'course finish is explicit'], 2, ['Combine chase-platformer movement structure with bounded game-specific projectile combat.']),
  'rail-shooter': plan('Advance through a scripted sequence of target groups, aim with a bounded cursor, fire, and finish the route.', 'twin-stick-shooter', ['player', 'background', 'enemy', 'ui.cursor', 'particle'], ['route/encounter sequence advances automatically', 'aim/fire interaction scores hits', 'final sequence ends in completion'], 3, ['Use a deterministic scripted route and cursor fallback; no reusable rail-camera or spatial pointer system.']),
} as const satisfies Readonly<Record<string, ExplicitStarterKitPlan>>;
