import { plan, type ExplicitStarterKitPlan } from './types.ts';

export const SIMULATIONMANAGEMENT_SCAFFOLD_PLANS = {
  'shopkeeper': plan('Buy or stock a small inventory, sell to bounded customer events, and grow currency through a short shop cycle.', 'idle-incremental', ['player', 'background', 'pickup', 'ui.panel', 'ui.button'], ['inventory/stock count changes', 'sale events exchange item for currency', 'currency enables at least one meaningful upgrade/restock'], 2, ['Represent customers as deterministic events, not fake shared AI.']),
  'tycoon-lite': plan('Invest currency into two production upgrades, watch income change over time, and reach a target business value.', 'idle-incremental', ['player', 'background', 'ui.panel', 'ui.button', 'pickup'], ['income loop is visible', 'two upgrades change production/cost state', 'target value completes the scenario'], 2, ['Keep economy deliberately small and inspectable.']),
  'farming-lite': plan('Plant a small set of plots, advance growth through deterministic time/jobs, harvest crops, and reach a harvest target.', 'idle-incremental', ['player', 'background', 'platform', 'pickup', 'ui.panel', 'ui.button'], ['plot state changes through plant/grow/harvest', 'growth is deterministic', 'harvest changes inventory/resource total'], 3, ['Use authored plot slots and simulation jobs; no season/crop framework.']),
  'pet-creature': plan('Care for one creature by managing a few needs/actions until a short wellbeing goal is reached.', 'idle-incremental', ['player', 'background', 'pickup', 'ui.panel', 'ui.button'], ['at least two needs change over time/actions', 'care action changes creature state', 'wellbeing/goal state is visible'], 3, ['Creature behavior is a bounded state machine, not shared creature AI.']),
  'colony-lite': plan('Assign a few workers to bounded jobs, accumulate resources, and complete one colony construction goal.', 'idle-incremental', ['player', 'background', 'pickup', 'platform', 'ui.panel', 'ui.button'], ['worker/job assignment changes production', 'resources accumulate deterministically', 'construction goal consumes resources and completes'], 3, ['No pathfinding/needs/construction framework; use abstract worker slots/jobs.']),
  'restaurant': plan('Queue simple orders, process them through timed preparation, serve them, and reach a revenue target.', 'idle-incremental', ['player', 'background', 'pickup', 'ui.panel', 'ui.button'], ['orders enter and leave a queue', 'timed preparation changes order state', 'serving changes revenue/score'], 3, ['Customers may be deterministic order events; no customer AI system.']),
  'aquarium-terrarium': plan('Maintain a small habitat by balancing two resources/needs and keeping its creature state healthy through a short cycle.', 'idle-incremental', ['player', 'background', 'pickup', 'ui.panel', 'ui.button'], ['habitat resources change over time', 'care actions affect state', 'success/failure threshold is explicit'], 3, ['Use bounded resource/need simulation only; no shared creature ecosystem.']),
} as const satisfies Readonly<Record<string, ExplicitStarterKitPlan>>;
