import { plan, type ExplicitStarterKitPlan } from './types.ts';

export const SIMULATIONMANAGEMENT_SCAFFOLD_PLANS = {
  'shopkeeper': plan('Serve matching goods from stock to a cycling demand queue (sw2d.economy shop mode) and restock from cash.', 'idle-incremental', ['player', 'background', 'pickup', 'ui.panel', 'ui.button'], ['customer arrives from authored demand', 'serving the matching good spends stock and pays cash', 'K restocks the selected good'], 2, ['Shop layout, walking customers, prestige and offline catch-up are not reusable.']),
  'tycoon-lite': plan('Start production jobs; waiting buyers auto-purchase when stock exists (sw2d.economy factory mode).', 'idle-incremental', ['player', 'background', 'ui.panel', 'ui.button', 'pickup'], ['a buyer is in the queue', 'K starts a production job', 'finished stock auto-sells'], 2, ['Prestige, offline catch-up and a large production chain are not reusable.']),
  'farming-lite': plan('Plant a small set of plots, advance growth through deterministic time/jobs, harvest crops, and reach a harvest target.', 'idle-incremental', ['player', 'background', 'platform', 'pickup', 'ui.panel', 'ui.button'], ['plot state changes through plant/grow/harvest', 'growth is deterministic', 'harvest changes inventory/resource total'], 3, ['Use authored plot slots and simulation jobs; no season/crop framework.']),
  'pet-creature': plan('Care for one creature by managing a few needs/actions until a short wellbeing goal is reached.', 'idle-incremental', ['player', 'background', 'pickup', 'ui.panel', 'ui.button'], ['at least two needs change over time/actions', 'care action changes creature state', 'wellbeing/goal state is visible'], 3, ['Creature behavior is a bounded state machine, not shared creature AI.']),
  'colony-lite': plan('Assign a few workers to bounded jobs, accumulate resources, and complete one colony construction goal.', 'idle-incremental', ['player', 'background', 'pickup', 'platform', 'ui.panel', 'ui.button'], ['worker/job assignment changes production', 'resources accumulate deterministically', 'construction goal consumes resources and completes'], 3, ['No pathfinding/needs/construction framework; use abstract worker slots/jobs.']),
  'restaurant': plan('Cook the selected recipe then serve the waiting ticket (sw2d.economy kitchen mode).', 'idle-incremental', ['player', 'background', 'pickup', 'ui.panel', 'ui.button'], ['a diner arrives from authored demand', 'K starts a recipe', 'ENTER serves once the requested good is in stock'], 3, ['Kitchen layout, walking customers and prestige are not reusable.']),
  'aquarium-terrarium': plan('Maintain a small habitat by balancing two resources/needs and keeping its creature state healthy through a short cycle.', 'idle-incremental', ['player', 'background', 'pickup', 'ui.panel', 'ui.button'], ['habitat resources change over time', 'care actions affect state', 'success/failure threshold is explicit'], 3, ['Use bounded resource/need simulation only; no shared creature ecosystem.']),
} as const satisfies Readonly<Record<string, ExplicitStarterKitPlan>>;
