import { plan, type ExplicitStarterKitPlan } from './types.ts';

export const SIMULATIONMANAGEMENT_SCAFFOLD_PLANS = {
  'shopkeeper': plan('Serve matching goods from stock to a cycling demand queue (sw2d.economy shop mode) and restock from cash.', 'idle-incremental', ['player', 'background', 'pickup', 'ui.panel', 'ui.button'], ['customer arrives from authored demand', 'serving the matching good spends stock and pays cash', 'K restocks the selected good'], 2, ['Shop layout, walking customers, prestige and offline catch-up are not reusable.']),
  'tycoon-lite': plan('Start production jobs; waiting buyers auto-purchase when stock exists (sw2d.economy factory mode).', 'idle-incremental', ['player', 'background', 'ui.panel', 'ui.button', 'pickup'], ['a buyer is in the queue', 'K starts a production job', 'finished stock auto-sells'], 2, ['Prestige, offline catch-up and a large production chain are not reusable.']),
  'farming-lite': plan('Plant a small set of plots, advance growth through deterministic time/jobs, harvest crops, and reach a harvest target.', 'idle-incremental', ['player', 'background', 'platform', 'pickup', 'ui.panel', 'ui.button'], ['plot state changes through plant/grow/harvest', 'growth is deterministic', 'harvest changes inventory/resource total'], 3, ['Use authored plot slots and simulation jobs; no season/crop framework.']),
  'pet-creature': plan('Care for one creature by feeding and playing (sw2d.needs creature mode) until a wellbeing hold is reached.', 'idle-incremental', ['player', 'background', 'pickup', 'ui.panel', 'ui.button'], ['hunger and mood decay over simulation time', 'J feeds and K plays through sw2d.needs', 'wellbeing hold completes the session'], 3, ['Full creature behaviour AI and relationship graphs are not reusable.']),
  'colony-lite': plan('Assign a few workers to bounded jobs, accumulate resources, and complete one colony construction goal.', 'idle-incremental', ['player', 'background', 'pickup', 'platform', 'ui.panel', 'ui.button'], ['worker/job assignment changes production', 'resources accumulate deterministically', 'construction goal consumes resources and completes'], 3, ['No pathfinding/needs/construction framework; use abstract worker slots/jobs.']),
  'restaurant': plan('Cook the selected recipe then serve the waiting ticket (sw2d.economy kitchen mode).', 'idle-incremental', ['player', 'background', 'pickup', 'ui.panel', 'ui.button'], ['a diner arrives from authored demand', 'K starts a recipe', 'ENTER serves once the requested good is in stock'], 3, ['Kitchen layout, walking customers and prestige are not reusable.']),
  'aquarium-terrarium': plan('Keep water and food in range (sw2d.needs habitat mode) through a short healthy hold.', 'idle-incremental', ['player', 'background', 'pickup', 'ui.panel', 'ui.button'], ['water and food decay over simulation time', 'J feeds and K refreshes through sw2d.needs', 'a healthy hold completes; dropping below the floor fails'], 3, ['A full creature ecosystem is not reusable.']),
} as const satisfies Readonly<Record<string, ExplicitStarterKitPlan>>;
