import { plan, type ExplicitStarterKitPlan } from './types.ts';

export const STRATEGYDEFENSE_SCAFFOLD_PLANS = {
  'lane-defense': plan('Place or activate defenders in fixed lanes, stop a bounded enemy wave, and complete the round if the endpoint survives.', 'tower-defense', ['player', 'background', 'enemy', 'platform', 'pickup', 'checkpoint', 'ui.cursor'], ['lane placement/selection works', 'enemy wave advances through lanes', 'base/end condition resolves win or loss'], 2, ['Reuse tower-defense structure but constrain movement to lanes; no generic lane framework.']),
  'auto-battler': plan('Choose a small squad/setup, start an automated combat round, and resolve a clear win/loss outcome.', 'tower-defense', ['player', 'background', 'enemy', 'pickup', 'ui.panel', 'ui.button'], ['pre-round selection changes combat setup', 'combat advances without continuous player control', 'round ends with deterministic win/loss'], 3, ['Autonomous combat orchestration stays game-specific.']),
  'simple-rts': plan('Select a small unit group, issue bounded movement/attack commands, destroy an objective, and win.', 'tower-defense', ['player', 'background', 'enemy', 'checkpoint', 'ui.cursor'], ['selection state is visible', 'at least one command changes unit behavior', 'objective destruction triggers victory'], 3, ['Use grid/waypoint-like bounded commands if spatial pointer is insufficient; no shared pathfinding/RTS command system.']),
  'turn-based-tactics': plan('Move units on a small grid in alternating turns, perform one attack action, and defeat the opposing unit set.', 'tower-defense', ['player', 'background', 'enemy', 'platform', 'ui.cursor', 'ui.panel'], ['turn ownership alternates deterministically', 'movement range/action selection is bounded and visible', 'attack resolution can produce victory'], 1, ['Keep range/path/action logic in the kit; do not generalize into shared tactics infrastructure.']),
  'base-defense': plan('Defend a central base through a bounded enemy wave, damage attackers, and resolve survival or base destruction.', 'tower-defense', ['player', 'background', 'enemy', 'hazard', 'checkpoint', 'particle'], ['enemy wave targets the base', 'base health changes from attacks', 'survival/wave-clear and base-destroyed outcomes are explicit'], 2, ['Reuse tower-defense wave concepts without requiring tower placement.']),
  'territory-control': plan('Capture and hold a small set of zones while opposing actors contest them, then win by a bounded score/ownership condition.', 'tower-defense', ['player', 'background', 'enemy', 'checkpoint', 'ui.panel'], ['zone ownership can change', 'contesting affects capture progress', 'score/hold condition ends the match'], 3, ['Capture/ownership/scoring remains game-specific.']),
} as const satisfies Readonly<Record<string, ExplicitStarterKitPlan>>;
