import { plan, type ExplicitStarterKitPlan } from './types.ts';

export const TOPDOWNACTION_SCAFFOLD_PLANS = {
  'top-down-adventure': plan('Explore a compact top-down room, collect an objective item, avoid hazards, and reach an exit.', 'twin-stick-shooter', ['player', 'background', 'pickup', 'hazard', 'checkpoint', 'exit'], ['top-down movement is responsive', 'objective pickup changes state', 'exit responds to objective state'], 2, ['Prefer a simple authored room over adding new adventure framework abstractions.']),
  'action-adventure': plan('Move through a top-down encounter, damage an enemy, collect an objective, and open the route to the exit.', 'twin-stick-shooter', ['player', 'background', 'enemy', 'pickup', 'hazard', 'exit', 'particle'], ['player can damage/defeat at least one enemy', 'objective/door state changes', 'player damage feedback is observable'], 2, ['Weapons/projectiles may be bounded game-specific code; do not claim a reusable weapon system.']),
  'survivor-like': plan('Survive a short timed arena while enemies spawn in bounded waves, then collect an upgrade and clear the run.', 'twin-stick-shooter', ['player', 'background', 'enemy', 'pickup', 'particle'], ['timed wave pressure is observable', 'automatic or bounded attack damages enemies', 'upgrade changes a visible stat or behavior'], 3, ['Keep wave orchestration and attacks game-specific; no procedural or meta-progression engine.']),
  'dungeon-crawler': plan('Traverse a small authored dungeon, defeat a guard encounter, collect a key-like objective, and reach the exit.', 'twin-stick-shooter', ['player', 'background', 'enemy', 'pickup', 'hazard', 'exit'], ['authored room traversal works', 'enemy encounter can be cleared', 'key/objective gates exit or next area'], 2, ['Use an authored dungeon; do not add procedural generation.']),
  'action-roguelite': plan('Clear a compact combat room, choose one temporary upgrade, and finish a single run with an explicit win/lose reset.', 'twin-stick-shooter', ['player', 'background', 'enemy', 'pickup', 'particle'], ['run state resets cleanly', 'one upgrade changes the current run', 'win/lose outcome is explicit'], 3, ['Keep the starter to one bounded run; do not invent persistent meta-progression/permadeath infrastructure.']),
  'stealth-game': plan('Cross a guarded space, avoid an enemy vision zone, collect an objective, and reach the exit without triggering alarm.', 'twin-stick-shooter', ['player', 'background', 'enemy', 'pickup', 'hazard', 'exit'], ['guard perception state is observable', 'alarm/failure condition can trigger', 'a stealth-success path reaches the exit'], 1, ['Keep perception model simple and game-specific; do not expand shared AI to pretend full stealth AI exists.']),
  'heist-game': plan('Enter a guarded room, steal a target item, manage an alarm state, and escape to the exit.', 'twin-stick-shooter', ['player', 'background', 'enemy', 'pickup', 'hazard', 'exit'], ['target can be stolen', 'alarm state changes from player actions', 'escape completion requires the target'], 3, ['Build on the stealth pattern with a bounded objective/alarm loop; no generalized heist framework.']),
  'arena-combat': plan('Fight through a compact top-down arena, defeat a fixed enemy set, and end the round when the arena is clear.', 'twin-stick-shooter', ['player', 'background', 'enemy', 'pickup', 'particle'], ['player attack damages enemies', 'arena clear condition is tracked', 'damage/death feedback is observable'], 2, ['Keep combat mechanics local; shared combat remains health/damage state only.']),
  'boss-rush': plan('Fight two distinct boss phases or bosses back-to-back with explicit health, telegraphs, and victory state.', 'twin-stick-shooter', ['player', 'background', 'enemy', 'hazard', 'pickup', 'particle'], ['boss health/phase state is visible', 'at least two attack patterns or phases differ', 'victory occurs only after final boss state'], 3, ['Boss orchestration belongs in game-specific code; do not add a generic boss framework.']),
} as const satisfies Readonly<Record<string, ExplicitStarterKitPlan>>;
