import { plan, type ExplicitStarterKitPlan } from './types.ts';

export const VEHICLEMOVEMENT_SCAFFOLD_PLANS = {
  'top-down-racer': plan('Drive a short closed track through ordered checkpoints and finish a timed lap.', 'twin-stick-shooter', ['player', 'background', 'checkpoint', 'hazard', 'pickup', 'exit'], ['vehicle steering/throttle/brake intent drives the racer', 'checkpoints must be crossed in order', 'lap/finish time is recorded'], 1, ['Keep race orchestration and handling in game-specific code.']),
  'kart-racer': plan('Complete a short checkpoint race while collecting one bounded pickup that changes vehicle behavior.', 'twin-stick-shooter', ['player', 'background', 'checkpoint', 'hazard', 'pickup', 'exit', 'particle'], ['ordered checkpoints define race progress', 'pickup produces a visible temporary effect', 'finish occurs after required checkpoint sequence'], 3, ['Do not add a generalized item/effect or racing system.']),
  'time-trial-racer': plan('Race alone through ordered checkpoints and beat or record a target time.', 'twin-stick-shooter', ['player', 'background', 'checkpoint', 'hazard', 'exit'], ['timer starts/stops at correct states', 'checkpoint order is enforced', 'result compares against a target/best time'], 2, ['Use arcade score/timing where helpful; race logic remains local.']),
  'endless-driving': plan('Drive through a looping authored road while dodging hazards and increasing distance score until a crash ends the run.', 'twin-stick-shooter', ['player', 'background', 'hazard', 'pickup'], ['forward travel is continuous', 'distance/score increases', 'collision ends or penalizes the run'], 3, ['Recycle a bounded authored segment; do not add procedural generation.']),
  'boat-flight-racer': plan('Pilot a vehicle through a short gate course with simple altitude/buoyancy-like state and finish after all gates.', 'twin-stick-shooter', ['player', 'background', 'checkpoint', 'hazard', 'exit', 'particle'], ['vehicle intent controls motion', 'a simple vertical/altitude-like state affects navigation', 'ordered gates lead to completion'], 3, ['Approximate the special movement model locally; no shared flight/buoyancy system.']),
} as const satisfies Readonly<Record<string, ExplicitStarterKitPlan>>;
